Kakki 2
nokia0315/Python-practice pull request #6
Opened 2022-07-25 13:47 UTC by nokia0315

Can you check my code?
I fixed a error of post.

2022-07-26 12:17 UTC, ptrkdan requested changes

2022-07-26 12:17 UTC, ptrkdan commented on app.py
> +@app.route('/', methods=["GET", "POST"])
[Q] 他の箇所を見ると`'`になっているのでですが、`"`に変更する理由は何でしょうか？

2022-07-26 12:17 UTC, ptrkdan commented on app.py
> +def read(id):
[IMO] 関数名とルートの統一感のため、関数名は`get_detail`等の方が良いと思います。

2022-07-26 12:17 UTC, ptrkdan commented on templates/create.html
> +<form action="/" method="POST">
👍

2022-07-26 12:17 UTC, ptrkdan commented on templates/detail.html
> +<P>{{ post.detail }}</P>
[KMK] `<P>` → `<p>` （小文字） 
（６行目の`<P>`も）

2022-07-26 12:17 UTC, ptrkdan commented on templates/index.html
> +<a href="detail/{{ post.id }}" role="button">Detail</a>
[IMO] こちらの `role="button"`は不要ではないかと思います。
`role="button"`を付けるとアクセシビリティの面でボタンとして見られるのですが、こちらの`<a>`がページリンクに見えるので`role="link"`の方が正しいです。（`href`を持っている`<a>`はデフォルトの`role`が`link`になるので、書かなくても良い）

参考：https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles/button_role

一般的には基本の`role`を上書きするのがいい場合はあまりないので`<button>`や`<input>`でも`role="button"`を書かなくて良いと思います。

2022-07-26 12:19 UTC, ptrkdan commented
[KMK] 本プルリクエストのタイトルもわかりやすくなるため、修正内容とかを書いた方が良いと思います。

`Create POSTの修正`とか

2022-07-26 12:20 UTC, ptrkdan commented on Readme.md
> +I'm making a simple webapp to practice to programming.
[MEMO] #5 の変更ですね。

2022-07-27 12:45 UTC, nokia0315 commented on app.py
> +@app.route('/', methods=["GET", "POST"])
【A】To fix a error of post. but,　This correction can't fix the error.
          I will Fix " part.

2022-07-27 14:09 UTC, nokia0315 commented
I fixed the things you pointed out.

2022-08-02 10:47 UTC, merged